# Generated by Django 4.0.4 on 2022-07-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
